# Generated by Django 2.2.11 on 2020-03-07 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import shareapp.main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to=shareapp.main.models.make_file_path, verbose_name='File')),
                ('password', models.CharField(default=shareapp.main.models.make_random_password, max_length=254, verbose_name='Password')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expires', models.DateTimeField(default=shareapp.main.models.make_expire_timestamp, verbose_name='Expires')),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Shared item',
                'verbose_name_plural': 'Shared items',
            },
        ),
    ]
