# Generated by Django 2.2.11 on 2020-03-08 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(verbose_name='Created')),
                ('files', models.IntegerField(default=0, verbose_name='File downloads')),
                ('links', models.IntegerField(default=0, verbose_name='URL views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrievals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retrieval',
                'verbose_name_plural': 'Retrievals',
                'unique_together': {('user', 'created')},
            },
        ),
    ]
